### ISSUE TITLE
Run iOS App

### ISSUE THREAD

**Issue by kareemradwan** [Anmol92verma/SlackComposeMultiplatform#5]
Hi @Anmol92verma 

I am trying run the iOS app but I don't know how? 

if there any instructions to do it, will help me a lot.

Thanks

**Comment by Anmol92verma** [comment]
I haven't tried running iOS since some time but once the gradle sync is successful you need to run the task which deploys the app on simulator. There's a specific task to deploy on iPad and iPhones. 

```
./gradlew iosDeployIPhone8Debug
```

Also make sure you use the grpc kmp library from the fork that i created as mentioned in the readme.

The android and jvm run's fine. Also make sure you match the ip address in GrpcCalls class of your system once you run the slackserver module.
